from pyannote.core import Annotation as Annotation, Segment as Segment

class Vad:
    def __init__(self, vad_onset) -> None: ...
    @staticmethod
    def preprocess_audio(audio) -> None: ...
    @staticmethod
    def merge_chunks(segments, chunk_size, onset: float, offset: float | None): ...
